cpossible_dbalisteerp:
    resource: "@cpossibleBundle/Resources/config/routing/dbalisteerp.yml"
    prefix:   /dbalisteerp

cpossible_homepage:
    path:     /index2
    defaults: { _controller: cpossibleBundle:Default:index }
