cpossible:
    resource: "@cpossibleBundle/Resources/config/routing/dbalisteerp.yml"
    prefix:   /liste

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# I'm trying to setup all routes to Home controller as routes that are interacting with the homepage

cpossible_fetch:
    path:      /
    defaults:  { _controller: cpossibleBundle:Home:fetch }

cpossible_around:
    path: /around
    defaults: { _controller: cpossibleBundle:Home:around }
    methods: POST

cpossible_list:
  path: /search_list
  defaults: { _controller: cpossibleBundle:Home:search_list}
  methods: POST

cpossible_erpslist:
    path: /erps_list_autocompleted
    defaults: { _controller: cpossibleBundle:Home:erpListAutocompleted}
    methods: POST

cpossible_checkdpt:
    path: /checkdpt
    defaults: { _controller: cpossibleBundle:Home:checkDepartement}
    methods: POST


report_index:
    path: /report
    defaults: { _controller: cpossibleBundle:Report:index }

report_form:
    path: /report/new
    defaults: { _controller: cpossibleBundle:Report:form }

report_new:
    path: /report/insert
    defaults: { _controller: cpossibleBundle:Report:insertOne }
    methods: POST
    
report_delete:
    path: /report/{id}/delete
    defaults: { _controller: cpossibleBundle:Report:deleteOne }

checking_siret:
    path: /siret
    defaults: { _controller: cpossibleBundle:Checking:siret }
    methods: POST

checking_normalize:
    path: /normalize
    defaults: { _controller: cpossibleBundle:Checking:normalizeDadabase }
    methods: GET

tps_index:
  path: /tps
  defaults: { _controller: cpossibleBundle:Tps:tps }

tps_new:
  path: /tps/new
  defaults: { _controller: cpossibleBundle:Tps:new}
  methods: POST

annot:
    resource: "@cpossibleBundle/Controller/DbaListeerpController.php"
    type:     annotation

# ---------------

dbalisteerp_last:
    path: /last/{number}
    defaults: { _controller: "cpossibleBundle:DbaListeerp:last"}
    methods: GET

dbalisteerp_index:
    path:     /index
    defaults: { _controller: "cpossibleBundle:DbaListeerp:index" }
    methods:  GET

dbalisteerp_show:
    path:     /{listeerpId}/show
    defaults: { _controller: "cpossibleBundle:DbaListeerp:show" }
    methods:  GET

dbalisteerp_new:
    path:     /liste/new
    defaults: { _controller: "cpossibleBundle:DbaListeerp:new" }
    methods:  GET

dbaListeerp_insert:
    path: /liste/insert
    defaults: { _controller: "cpossibleBundle:DbaListeerp:insert"}
    methods: POST

dbalisteerp_edit:
    path:     /{listeerpId}/edit
    defaults: { _controller: "cpossibleBundle:DbaListeerp:edit" }
    methods:  [GET, POST]

dbaListeerp_editOne:
    path: /{listeerpId}/update
    defaults: { _controller: "cpossibleBundle:DbaListeerp:editOne"} 
    methods: POST

dbalisteerp_delete:
    path:     /{listeerpId}/delete
    defaults: { _controller: "cpossibleBundle:DbaListeerp:delete" }
    methods:  [DELETE, GET] # maybe we can work with only delete but idk, i didnt look into it, ima work with GET

dbalisteerp_fetch:
    path:     /fetch
    defaults: { _controller: "cpossibleBundle:DbaListeerp:fetch" }

# ERP_Autocomplete_name:
#     path: /autocomplete_name
#     defaults: { _controller: "cpossibleBundle:ERP:autocomplete_name"}

# ERP_Autocomplete_adress:
#     path: /autocomplete_adress
#     defaults: { _controller: "cpossibleBundle:ERP:autocomplete_adress"}

