cpossibleBundle\Entity\Signalements:
    type: entity
    table: signalements
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        adresseErp:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: adresse_erp
        adresseSignalee:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: adresse_signalee
        userEmail:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: user_email
        message:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
    lifecycleCallbacks: {  }
